/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Container#getContains <em>Contains</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContainer()
 * @model
 * @generated
 */
public interface Container extends EObject
{
  /**
   * Returns the value of the '<em><b>Contains</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contains</em>' containment reference.
   * @see #setContains(ABC)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContainer_Contains()
   * @model containment="true"
   * @generated
   */
  ABC getContains();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Container#getContains <em>Contains</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contains</em>' containment reference.
   * @see #getContains()
   * @generated
   */
  void setContains(ABC value);

} // Container
